spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/databases/event
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: "org.hibernate.dialect.H2Dialect"
    show-sql: false
  liquibase:
    change-log: classpath:migrations/migrations.xml
debug: true