spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/databases/event
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"